safe: true
lsi: false
pygments: true
markdown: rdiscount
permalink: pretty
name: "ツ onCode"
url: http://akolosov.github.io
paginate: 5
paginate_path: "/blog/page:num"
exclude:
- Gemfile
- Gemfile.lock
